### ISSUE TITLE
Syn3Updater Crash on Open

### ISSUE THREAD

**Issue by elpamyelhsa** [CyanLabs/Syn3Updater#174]
**Describe the bug**
Opening the software, shows splash screen with "Checking for Update". This disappears, and the app has crashed.

**To Reproduce**
1. Open shortcut
2. Press "Yes" on UAC prompt
3. Wait for "Checking for Update" box to disappear
4. App has now crashed

**Expected behavior**
App not to crash, rather it should show the app interface.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Windows Version: 10 21H2
 - Syn3 Updater Version 2.10.11
 - Syn3 Updater Branch Stable

**Additional context**
Event Logs:
```
Application: Launcher.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.Uri..ctor(System.String)
   at Cyanlabs.Launcher.UpdateCheck+<Execute>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Cyanlabs.Launcher.UpgradingWindow+<StartCheck>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Cyanlabs.Launcher.UpgradingWindow+<AcrylicWindow_Loaded>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Cyanlabs.Launcher.App.Main()

```

**Comment by Fma965** [comment]
I can't replicate this, make sure you are not blocking GitHub or api.cyanlabs.net in your firewall or country internet restrictions

**Comment by Fma965** [comment]
If you are still having issues you can manually download the latest release from https://github.com/CyanLabs/Syn3Updater/releases/download/2.10.11/2.10.11.zip

and extract this to your installation directory replacing all files, then if the issue persists provide the crash log (this will have more error information)

**Comment by elpamyelhsa** [comment]
Still not working,

https://api.cyanlabs.net [172.67.168.16] returns "hello world!"
https://api.github.com/ [13.238.54.232] returns expected json url list

Any hints on where to find the extra logging?

**Comment by elpamyelhsa** [comment]
UpdateCheck.cs::55 
`ciRelease = JsonConvert.DeserializeObject<CIRelease>(wc.DownloadString(new Uri("https://api.cyanlabs.net/ci/Syn3Updater/latest")));`
Seems to return:
`{"status":"error","error":"Invalid Project ID or Number"}`
But the "class CIRelease" will not fit this data

**Comment by Fma965** [comment]
You are trying to download the Ci branch for some reason, this is not currently operational. 

Delete this file C:\programdata\CyanLabs\Syn3Updater\LauncherPrefs.json

**Comment by elpamyelhsa** [comment]
Thanks, Looks like I had set the "Release Branch" to "Alpha" when I was using the software last.

I can confirm this will crash the app until the C:\ProgramData\CyanLabs\Syn3Updater\LauncherPrefs.json is deleted or edited to change ReleaseBranch back to 0

This file was the file causing the crash
`{"ReleaseBranch":2,"ReleaseInstalled":"2108","ReleaseTypeInstalled":1}`

**Comment by Fma965** [comment]
Great, my CI continuous integration server is down currently, I will try and redirect the api on the server side to prevent this

**Comment by Fma965** [comment]
Syn3 Updater alpha branch will now redirect to the current latest github release, i can not make it automatically stay on the latest without code changes so i have added a notice on the app to suggest all users leave the Alpha branch
