### ISSUE TITLE
Syn3 updater has crashed.

### ISSUE THREAD

**Issue by timothy054** [CyanLabs/Syn3Updater#187]
Unique ID: 1ed3eaa2-bb65-6906-bdbf-0242ac120002
Error: System.Windows.Markup.XamlParseException
Message: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.
Operating System: Microsoft Windows 7 Home Premium
Date Created:27 September 2022 @ 21:20:11

DETAILS
        System.Windows.Markup.XamlParseException<br>Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.<br><br>System.InvalidOperationException<br>Property path is not valid. 'FrameworkAppContextSwitches' does not have a public property named 'UseLegacyAccessibilityFeatures'.<br><br><br><br>   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at System.Windows.PropertyPath.ResolvePathParts(ITypeDescriptorContext typeDescriptorContext)
   at System.Windows.PropertyPath..ctor(String path, ITypeDescriptorContext typeDescriptorContext)
   at System.Windows.PropertyPathConverter.ConvertFrom(ITypeDescriptorContext typeDescriptorContext, CultureInfo cultureInfo, Object source)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)<br><br>0<br>8
ResolvePropertyName
PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
System.Windows.PropertyPath
System.Object ResolvePropertyName(System.String, System.Object, System.Type, System.Object, Boolean)<br>-2146233079<br>PresentationFramework<br><br><br>   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.SystemResources.LookupResourceInDictionary(ResourceDictionary dictionary, Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.SystemResources.FindThemeStyle(DependencyObjectType key)
   at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
   at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.OnVisualParentChanged(DependencyObject oldParent)
   at System.Windows.Controls.ListBoxItem.OnVisualParentChanged(DependencyObject oldParent)
   at System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at System.Windows.Media.VisualCollection.ConnectChild(Int32 index, Visual value)
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.VirtualizingStackPanel.InsertContainer(Int32 childIndex, UIElement container, Boolean isRecycled)
   at System.Windows.Controls.VirtualizingStackPanel.AddContainerFromGenerator(Int32 childIndex, UIElement child, Boolean newlyRealized, Boolean isBeforeViewport)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, IContainItemStorage& parentItemStorageProvider, Object& parentItem, Boolean& hasUniformOrAverageContainerSizeBeenSet, Double& computedUniformOrAverageContainerSize, Double& computedUniformOrAverageContainerPixelSize, Boolean& computedAreContainersUniformlySized, Boolean& hasAnyContainerSpanChanged, IList& items, Object& item, IList& children, Int32& childIndex, Boolean& visualOrderChanged, Boolean& isHorizontal, Size& childConstraint, Rect& viewport, VirtualizationCacheLength& cacheSize, VirtualizationCacheLengthUnit& cacheUnit, Boolean& foundFirstItemInViewport, Double& firstItemInViewportOffset, Size& stackPixelSize, Size& stackPixelSizeInViewport, Size& stackPixelSizeInCacheBeforeViewport, Size& stackPixelSizeInCacheAfterViewport, Size& stackLogicalSize, Size& stackLogicalSizeInViewport, Size& stackLogicalSizeInCacheBeforeViewport, Size& stackLogicalSizeInCacheAfterViewport, Boolean& mustDisableVirtualization, Boolean isBeforeFirstItem, Boolean isAfterFirstItem, Boolean isAfterLastItem, Boolean skipActualMeasure, Boolean skipGeneration, Boolean& hasBringIntoViewContainerBeenMeasured, Boolean& hasVirtualizingChildren)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ItemsPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ScrollContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.ScrollViewer.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at Cyanlabs.Syn3Updater.AppMan.Initialize() in C:\Users\fma96\Documents\GitHub\Syn3Updater\Syn3Updater\AppMan.cs:line 306
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)<br><br>0<br>8
RewrapException
PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
System.Windows.Markup.XamlReader
Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)<br>-2146233087<br>PresentationFramework<br><br>0<br>0

Raw JSON Output

            "{\"ErrorName\":\"System.Windows.Markup.XamlParseException\",\"ErrorLocation\":\"\/TryCatchWhen\/0\",\"Logs\":[{\"Log\":\"Syn3 Updater 2.11.4.0 (Stable) is Starting\",\"Time\":\"2022-09-27T17:20:08.5730187-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"URL Intent: \",\"Time\":\"2022-09-27T17:20:08.5886187-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"MainSettings found in LocalAppDataPath\",\"Time\":\"2022-09-27T17:20:08.5886187-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"MainSettings loaded successfully\",\"Time\":\"2022-09-27T17:20:08.744619-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Profile default loaded\",\"Time\":\"2022-09-27T17:20:08.744619-04:00\",\"Caller\":\"LoadProfile\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Determining language to use for the application\",\"Time\":\"2022-09-27T17:20:08.744619-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Language is set to en\",\"Time\":\"2022-09-27T17:20:08.744619-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Determining download path to use for the application\",\"Time\":\"2022-09-27T17:20:08.744619-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Download path is set to C:\\\\Users\\\\TIMZ\\\\Downloads\\\\Syn3Updater\\\\\",\"Time\":\"2022-09-27T17:20:08.744619-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"MainSettings saved successfully\",\"Time\":\"2022-09-27T17:20:09.4934203-04:00\",\"Caller\":\"SaveSettings\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Profile default saved successfully\",\"Time\":\"2022-09-27T17:20:09.4934203-04:00\",\"Caller\":\"SaveSettings\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"Launching main window\",\"Time\":\"2022-09-27T17:20:09.4934203-04:00\",\"Caller\":\"Initialize\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"LauncherPrefs saved successfully\",\"Time\":\"2022-09-27T17:20:12.0050247-04:00\",\"Caller\":\"UpdateLauncherSettings\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"MainWindow Initialized\",\"Time\":\"2022-09-27T17:20:13.299827-04:00\",\"Caller\":\".ctor\",\"LogType\":\"Debug\",\"Exception\":null},{\"Log\":\"System.Windows.Markup.XamlParseException\",\"Time\":\"2022-09-27T17:20:13.5026273-04:00\",\"Caller\":\"CrashWindow\",\"LogType\":\"Crash\",\"Exception\":{\"ClassName\":\"System.Windows.Markup.XamlParseException\",\"Message\":\"Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.\",\"Data\":{\"System.Object\":null},\"InnerException\":{\"ClassName\":\"System.InvalidOperationException\",\"Message\":\"Property path is not valid. 'FrameworkAppContextSwitches' does not have a public property named 'UseLegacyAccessibilityFeatures'.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)\\r\\n   at System.Windows.PropertyPath.ResolvePathParts(ITypeDescriptorContext typeDescriptorContext)\\r\\n   at System.Windows.PropertyPath..ctor(String path, ITypeDescriptorContext typeDescriptorContext)\\r\\n   at System.Windows.PropertyPathConverter.ConvertFrom(ITypeDescriptorContext typeDescriptorContext, CultureInfo cultureInfo, Object source)\\r\\n   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":\"8\\nResolvePropertyName\\nPresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\\nSystem.Windows.PropertyPath\\nSystem.Object ResolvePropertyName(System.String, System.Object, System.Type, System.Object, Boolean)\",\"HResult\":-2146233079,\"Source\":\"PresentationFramework\",\"WatsonBuckets\":null},\"HelpURL\":null,\"StackTraceString\":\"   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)\\r\\n   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)\\r\\n   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)\\r\\n   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)\\r\\n   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)\\r\\n   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)\\r\\n   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)\\r\\n   at System.Windows.SystemResources.LookupResourceInDictionary(ResourceDictionary dictionary, Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)\\r\\n   at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)\\r\\n   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)\\r\\n   at System.Windows.SystemResources.FindThemeStyle(DependencyObjectType key)\\r\\n   at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)\\r\\n   at System.Windows.FrameworkElement.UpdateThemeStyleProperty()\\r\\n   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)\\r\\n   at System.Windows.FrameworkElement.TryFireInitialized()\\r\\n   at System.Windows.FrameworkElement.OnVisualParentChanged(DependencyObject oldParent)\\r\\n   at System.Windows.Controls.ListBoxItem.OnVisualParentChanged(DependencyObject oldParent)\\r\\n   at System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)\\r\\n   at System.Windows.Media.Visual.AddVisualChild(Visual child)\\r\\n   at System.Windows.Media.VisualCollection.ConnectChild(Int32 index, Visual value)\\r\\n   at System.Windows.Media.VisualCollection.Add(Visual visual)\\r\\n   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)\\r\\n   at System.Windows.Controls.VirtualizingStackPanel.InsertContainer(Int32 childIndex, UIElement container, Boolean isRecycled)\\r\\n   at System.Windows.Controls.VirtualizingStackPanel.AddContainerFromGenerator(Int32 childIndex, UIElement child, Boolean newlyRealized, Boolean isBeforeViewport)\\r\\n   at System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, IContainItemStorage& parentItemStorageProvider, Object& parentItem, Boolean& hasUniformOrAverageContainerSizeBeenSet, Double& computedUniformOrAverageContainerSize, Double& computedUniformOrAverageContainerPixelSize, Boolean& computedAreContainersUniformlySized, Boolean& hasAnyContainerSpanChanged, IList& items, Object& item, IList& children, Int32& childIndex, Boolean& visualOrderChanged, Boolean& isHorizontal, Size& childConstraint, Rect& viewport, VirtualizationCacheLength& cacheSize, VirtualizationCacheLengthUnit& cacheUnit, Boolean& foundFirstItemInViewport, Double& firstItemInViewportOffset, Size& stackPixelSize, Size& stackPixelSizeInViewport, Size& stackPixelSizeInCacheBeforeViewport, Size& stackPixelSizeInCacheAfterViewport, Size& stackLogicalSize, Size& stackLogicalSizeInViewport, Size& stackLogicalSizeInCacheBeforeViewport, Size& stackLogicalSizeInCacheAfterViewport, Boolean& mustDisableVirtualization, Boolean isBeforeFirstItem, Boolean isAfterFirstItem, Boolean isAfterLastItem, Boolean skipActualMeasure, Boolean skipGeneration, Boolean& hasBringIntoViewContainerBeenMeasured, Boolean& hasVirtualizingChildren)\\r\\n   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)\\r\\n   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)\\r\\n   at System.Windows.Controls.ItemsPresenter.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)\\r\\n   at System.Windows.Controls.ScrollContentPresenter.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)\\r\\n   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)\\r\\n   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Border.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.ScrollViewer.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Border.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Control.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)\\r\\n   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)\\r\\n   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)\\r\\n   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Control.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)\\r\\n   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)\\r\\n   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)\\r\\n   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)\\r\\n   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)\\r\\n   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Controls.Border.MeasureOverride(Size constraint)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Window.MeasureOverrideHelper(Size constraint)\\r\\n   at System.Windows.Window.MeasureOverride(Size availableSize)\\r\\n   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)\\r\\n   at System.Windows.UIElement.Measure(Size availableSize)\\r\\n   at System.Windows.Interop.HwndSource.SetLayoutSize()\\r\\n   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)\\r\\n   at System.Windows.Window.SetRootVisual()\\r\\n   at System.Windows.Window.SetRootVisualAndUpdateSTC()\\r\\n   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)\\r\\n   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)\\r\\n   at System.Windows.Window.ShowHelper(Object booleanBox)\\r\\n   at Cyanlabs.Syn3Updater.AppMan.Initialize() in C:\\\\Users\\\\fma96\\\\Documents\\\\GitHub\\\\Syn3Updater\\\\Syn3Updater\\\\AppMan.cs:line 306\\r\\n   at System.Windows.Application.<.ctor>b__1_0(Object unused)\\r\\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\\r\\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":\"8\\nRewrapException\\nPresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\\nSystem.Windows.Markup.XamlReader\\nVoid RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)\",\"HResult\":-2146233087,\"Source\":\"PresentationFramework\",\"WatsonBuckets\":null,\"Line\":0,\"Position\":0}}]}"

**Describe the bug**
Please explain in as much detail as possible what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 10, 8, 7]
 - Syn3 Updater Version [e.g. 2.0.0.0]
 - Syn3 Updater Branch [e.g. Stable, Beta or Alpha]

**Additional context**

I DID DEDLETE SUGJESTED FILES AND FOLDERS,
C:\ProgramData\CyanLabs\Syn3Updater
%localappdata%\CyanLabs\Syn3Updater

**Comment by Fma965** [comment]
You are running Windows 7, syn3updater does not support this, neither does Microsoft any more.
